var res = {
    "bg" :"img/bg.jpg",
    "img_1" :"img/img_1.png",
    "img_2" :"img/img_2.png",
    "img_3" :"img/img_3.png",
    "img_4" :"img/img_4.png",
    "img_5" :"img/img_5.png"
    // "cart1"  : "cart/res/graphics/cart1.png",
    // "obstacle1"  : "cart/res/graphics/obstacle1.png",
    // "obstacle2"  : "cart/res/graphics/obstacle2.png",
    // "obstacle3"  : "cart/res/graphics/obstacle3.png",
    // "obstacle4"  : "cart/res/graphics/obstacle4.png",
    // "obstacle5"  : "cart/res/graphics/obstacle5.png",
    // "item1"  : "cart/res/graphics/item1.png",
    // "item2"  : "cart/res/graphics/item2.png",
    // "pause"  : "cart/res/graphics/pauseButton.png",
    // "rule"  : "cart/res/graphics/rule.png",
    // "awardAlert"  : "cart/res/graphics/awardAlert.png",
    // "guide"  : "cart/res/graphics/guide.jpg",
    // "close"  : "cart/res/graphics/close.png",
    // "hand"  : "cart/res/graphics/hand.png",
    // "barrier"  : "cart/res/graphics/barrier.png",
    // "time3"  : "cart/res/graphics/time3.png",
    // "time2"  : "cart/res/graphics/time2.png",
    // "time1"  : "cart/res/graphics/time1.png",
    // "again"  : "cart/res/graphics/again.png",
    // "lAlert"  : "cart/res/graphics/lAlert.png",
    // "friend"  : "cart/res/graphics/friend.png",
    // "callf"  : "cart/res/graphics/callf.png",
    // "man"  : "cart/res/graphics/man.png",
    // "turn"  : "cart/res/graphics/turn.png",
    // "lottoD"  : "cart/res/graphics/lottoD.png",
    // "frame"  : "cart/res/graphics/frame.png",
    // "dbg"  : "cart/res/graphics/dbg.jpg",
    // "againD"  : "cart/res/graphics/againD.png",
    // "awardD"  : "cart/res/graphics/awardD.png",
    // "callfD"  : "cart/res/graphics/callfD.png",
    // "userinfo"  : "cart/res/graphics/userinfo.png",
    // "bj"  : "cart/res/graphics/bj.png",
    // "finish"  : "cart/res/graphics/finish.png",
    // "title"  : "cart/res/graphics/title.png",
    // "success"  : "cart/res/graphics/success.jpg",
    // "sagain"  : "cart/res/graphics/sagain.png",
    // "slotto"  : "cart/res/graphics/slotto.png",
    // "lottery"  : "cart/res/graphics/lottery.png",
    // "btn"  : "cart/res/graphics/btn.png",
    // "kindle"  : "cart/res/graphics/kindle.png",
    // "bread"  : "cart/res/graphics/bread.png",
    // "yin"  : "cart/res/graphics/yin.png",
    // "xin"  : "cart/res/graphics/xin.png",
    // "die"  : "cart/res/graphics/xin_die.png",
    // "cover"  : "cart/res/graphics/cover.png",
    // "boom"  : "cart/res/graphics/boom.png",
    // "speed"  : "cart/res/graphics/speed.png",
    // "music"  : "cart/res/graphics/music.png",
    // "nothing"  : "cart/res/graphics/nothing.png",
    // "line"  : "cart/res/graphics/line.png",
    // "soundOff"  : "cart/res/graphics/musicoff.png",
};

var g_resources = (function(){
    var g_resources =[]
    
    for(var i in res){
        g_resources.push(res[i])
    }
    return g_resources;
})()
